<a href="https://colab.research.google.com/github/MelissaMarin/Deep-Learning/blob/main/P1T1_basic_concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


###Conceptos basicos en python

####Comparativa de programación normal vs Python

#####Primer ejercicio en python-Número maximo

In [ ]:
#Metodo Python
var1,var2,var3= input ("Ingrese 3 numeros separados por coma:") .split(",")
print ("El numero maximo es:"+ str(max(var1,var2,var3)))

Ingrese 3 numeros separados por coma:2,3,5
El numero maximo es:5


#####Segundo ejercicio python-Suma

In [ ]:
# Método Clásico
tot=int (input("Ingrese Cantidad de números"))
suma=0
for i in range(0,tot):
  suma += int(input("Ingrese el valor del num " + str(i) + ": "))
print(" El total es: " + str(suma))

In [ ]:
#Metodo Python
suma=0
for i in range(0, int(input("Ingrese la cantidad N de números:"))):
  suma+=int((input("Ingrese el valor del número "+str(i)+":")))
print("El total de la suma es: "+str(suma))

Ingrese la cantidad N de números:3
Ingrese el valor del número 0:2
Ingrese el valor del número 1:3
Ingrese el valor del número 2:2
El total de la suma es: 7


#####Tercer ejercicio python-Números pares

In [ ]:
# Método Clásico
inicio=int(input("Número mínimo: "))
fin=int(input("Número máximo: "))
for i in range(inicio, fin):
  if((i%2)==0):
    print(" El número par es:" + str(i))

In [ ]:
#Metodo Python
for i in range(int(input("Primer número:")),int (input("Segundo número:"))):
  if((i%2)==0):
    print("El número primo es:" +str(i))

Primer número:5
Segundo número:8
El número primo es:6


#####Cuarto ejercicio-Manejo de listas

In [ ]:
# Método Clásico
rango1 = list(range(1,13))
rango2 = list(range(12,0,-1))
print(rango1 + rango2)

In [ ]:
#Metodo Python
lista=list(range(1,13))
print(lista+lista[::-1])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


#####Quinto ejercicio-Listas aleatorias

In [ ]:
#Metodo Clasico
import random
lista = [random.randrange(10) for i in range(10)]
print(lista)

In [ ]:
#Metodo Python
import random 
for i in range(10): print(random.randrange(100))

32
68
90
63
41
92
23
29
16
92


#Numpy

##Ejercicio 1: Uso de numpy

In [1]:

#Diseñar un programa donde 6 candidatos se disputan la alcaldía. Los votos de cada candidato son generados de forma aleatoria entre entre 1 y 25 mil votos maximo, el software debe decir quien gano
import numpy as np
from random import randint
matriz = np.array([[i+1, randint(1,25000)] for i in range(6)])
ganador = np.where(matriz[:,1] == matriz[:,1].max())
print("Las votaciones:\n " + str(matriz)+"\n El ganador es: " + str(matriz[ganador[0]]))


Las votaciones:
 [[    1 21735]
 [    2 10655]
 [    3  6866]
 [    4 19657]
 [    5  3624]
 [    6 13031]]
 El ganador es: [[    1 21735]]


##Ejercicio 2: Uso de numpy

In [6]:
#Los votos de cada candidatas son generados de forma aleatoria entre 1 y 4500 votos máximo para cada uno de los 123 municipios del departamento, el software debe determinar quien fue ganador@
#Nota Creamos una matriz llamada votos, compuesta por 123 filas (municipios y 8 columnas (candidatesi y cuyo vaine de cada celda sea un randomito entre 1 y 3000
import numpy as np
from random import randint
votos_20xx = np.random.randint(4500, size=(123,6))
tot_votos = np.array([[candidato+1,votos_20xx[:,candidato].sum()] for candidato in range(len(votos_20xx[0]))])
ganador = np.where(tot_votos == tot_votos[:,1].max())
print("El candidato ganador fue: " + str(tot_votos[ganador[0]]) + "\n Total de votos por cada candidato: \n" + str(tot_votos))

El candidato ganador fue: [[     2 280847]]
 Total de votos por cada candidato: 
[[     1 235898]
 [     2 280847]
 [     3 257185]
 [     4 276713]
 [     5 273999]
 [     6 269361]]


##Ejercicio 3: Crear un programa para simular una carrera de formula 1

In [8]:
# Renault, Ferrari, Mercedez, Ford, Red bull
import numpy as np
matriz = np.random.uniform(8.2, 10, size=(4,5))
tot_vueltas = np.array([[corredor+1, matriz[:,corredor].sum()] for corredor in range(len(matriz[0]))])
ganador = np.where(matriz == matriz[:,1].min())
print("El ganador de esta carrera fue:\n " + str(matriz) + "\n El piloto ganador fue: "+ str(tot_vueltas[ganador[0]]))

El ganador de esta carrera fue:
 [[8.94046472 9.38734201 9.82239332 8.55265666 9.87825756]
 [8.89078134 9.61146005 8.39665107 8.68157197 9.58040335]
 [9.47939372 9.66965881 9.27149501 9.82104537 8.68529431]
 [9.1684877  9.38376421 8.54509054 9.13278319 9.69339534]]
 El piloto ganador fue: [[ 4.         36.18805719]]
